apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 80c64ac0-0fa1-441b-a895-65d5eb7919b0
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: emojivoto
  name: web-app
  namespace: emojivoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    canary:
      canaryService: web-app-canary
      stableService: web-app
      steps:
      - setWeight: 100
      - pause:
          duration: 1
      trafficRouting:
        ambassador:
          mappings:
          - web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: datawire/emojivoto-web-app:v12
        imagePullPolicy: Always
        name: web-app
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web-app
status:
  blueGreen: {}
  canary: {}
